### ISSUE TITLE
Unable to save application coniguration settings

### ISSUE THREAD

**Issue by kenm09** [Esri/map-tour-storytelling-template-js#22]
Browsing to the website, "http://localhost/MapTour/?fromscratch", I have the option to change the zoom level by clicking Settings > Zoom level. When I do this, it tells me there is 1 unsaved change; Tour is not saved. If I click 'Save', it tells me "Save failed, please try again". Should this work with the User Download?

**Comment by glazou** [comment]
Sorry I missed your comments. 
Not sure what you faced, it should definitely works the same in the downloadable than in Online.
We have released multiple version since September 2014, hope this resolved your issues, please let me know otherwise.
