### ISSUE TITLE
Is it possible to make it work on a private network with arcgis portal for arcgis server

### ISSUE THREAD

**Issue by mhovens** [Esri/map-tour-storytelling-template-js#32]
I'm trying to make this work on a private network with no connection to the internet. Is this possible?

**Comment by glazou** [comment]
Absolutely, Map Tour is included with Portal for ArcGIS starting at version 10.2.1.
If you are using an earlier version you will find the information in the [FAQ](https://github.com/Esri/map-tour-storytelling-template-js#can-i-deploy-map-tour-on-portal-for-arcgis).

The most recent version may not be compatible with the oldest version of Portal for ArcGIS. If you experience issue, please try to deploy [Map Tour version 2.2.3](https://github.com/Esri/map-tour-storytelling-template-js/releases/tag/V2.2.3) that should work.
