### ISSUE TITLE
Question: How can I fix the layout mode (Desktop or Mobile)?

### ISSUE THREAD

**Issue by mahiran** [Esri/map-tour-storytelling-template-js#33]
In the Readme of this template, there is some descriptions:
"Note: if you embed a map tour in a web page make sure that the iframe is wide enough so that the map tour is displayed in Desktop mode. If the iframe is too small, the map tour will automatically switch its layout to the mobile layout, which is harder to use on a Desktop system because it is touch-orientated."

If I would like to fix the layout mode (Desktop or Mobile) of my own published MapTour application, how can I do it?  Are there any "switches" in the source code?  Or, must I customize the many source codes massively?

**Comment by glazou** [comment]
No that's not a configuration option at this time.

Forcing the application in one layout would not require tons of customization, it should just be a matter of modifying css rules in that file https://github.com/Esri/map-tour-storytelling-template-js/blob/master/MapTour/src/app/storymaps/maptour/ui/Responsive.css

If this is your first customization, please follow the developer guide https://github.com/Esri/map-tour-storytelling-template-js#developer-guide
