### ISSUE TITLE
Chrome hangs when loading template with specific location data and starting extent

### ISSUE THREAD

**Issue by bsmall** [Esri/map-tour-storytelling-template-js#34]
I've encountered a rather obscure issue that is specific to Chrome, a specific set of storymap locations, and the starting map extent when the template is launched. Chrome hangs while the template is loading (the spinning 'busy' indicator is visible, but no other UI elements) - to the point that Chrome becomes non-responsive and/or eventually displays prompt to 'Kill page'. When using other browsers such as IE or Firefox, it all works without issue.

Typically, when creating the webmap for the map tour template, I set the map extent so that the location points fit with the visible map extent (essentially, zoom to layer for the location points). For this particular storymap, the locations are fairly close in proximity and the map is zoomed in fairly close. When loading the storymap, this sort of starting extent hangs Chrome. If I set the webmap extent so that the location points are clustered close together in the middle of the map and zoomed out quite a bit, the template loads correctly in Chrome, though not at the 'ideal' starting extent. When using this workaround, further interaction with the template in Chrome such as zooming to closer extents seems to work fine.

I've posted a Gist for the location CSV file: https://gist.github.com/bsmall/ed7eb510fb72c2c54654/download#file-maptourlocations-csv 

To reproduce issue: In ArcGIS Online, I started a new webmap, added the CSV file to the map, zoomed the map to the extent of the locations layer, saved the webmap, published a web application using the MapTour template, then try viewing storymap in Chrome (I'm using Chrome 40.0.2214.111). 

To view the storymap in production using my 'zoomed out' starting extent workaround, see: http://www.iqmap.org/storymaps/MapTour/index.html?appid=b2aa8e83078f49b592ed13b81f96aa58&webmap=63f8984dc6b24e15bbbfeaaf83b39490

**Comment by glazou** [comment]
Thanks for your feedback, your diagnosis is 100% correct.
The JS Team have reported the issue to Chrome: https://code.google.com/p/chromium/issues/detail?id=437904 

We hope this will get fixed soon. From now, the only workaround is to have a larger initial extent.

**Comment by glazou** [comment]
We have a fix. It will get deployed later today in ArcGIS Online and here (release V2.2.7)

**Comment by glazou** [comment]
Reopening as the issue has reappeared. Going to deploy a new fix in next release.
