### ISSUE TITLE
Question. Toggle Tiled Map service with check box?

### ISSUE THREAD

**Issue by MicahShane** [Esri/map-tour-storytelling-template-js#36]
I have some imagery in my Map Tour.  I have added a checkbox to my Map Tour application.  Which file in the template do I need to modify to toggle this imagery on and off with the checkbox?  Is their a way to target the web map and the services in that map within the template to change their visibility when the box is checked on and off?

**Comment by glazou** [comment]
Yes MapTour is registering a global variable named `app`, though `app.map` you can access the map and do your magic :)

I recommend that you add your code in index.html, you can register your click event after this line https://github.com/Esri/map-tour-storytelling-template-js/blob/master/MapTour/src/index.html#L1172

**Comment by MicahShane** [comment]
Cool! It works!...I decided to go with two buttons instead of check box but it works perfect. Thank you so much!
Here is what I did, just for other's reference....
I added two html buttons in the index.html file like this.....
             
                                <button id="imgbtnon">Flood Imagery</button>
        			<button id="imgbtnoff">Streets</button>

Then I added JS to the end of the index.html like this....

if (isInBuilderMode) {
						 			require(["storymaps/builder/Builder", "storymaps/maptour/builder/BuilderView"], function(Builder, BuilderView) {
						 				Core.init(new MainView(), Builder);
						 				Builder.init(Core, new BuilderView());
						 			});
						 		}
						 		else
						 			Core.init(new MainView());
						 			function addListeners(){
						 				document.getElementById('imgbtnon').onclick = function(){
						 					var FloodLayer = app.map.getLayer(app.map.layerIds[1]);
						 					FloodLayer.setVisibility(true);	
						 				}
						 				document.getElementById('imgbtnoff').onclick = function(){
						 					var FloodLayer =   app.map.getLayer(app.map.layerIds[1]);
						 					FloodLayer.setVisibility(false);	
						 				}
						 			}
						 			window.onload = addListeners;
						 	});
				 		}
					);
				});
			 }
		</script>
	</body>
