### ISSUE TITLE
Android (native) Browser still not supported?

### ISSUE THREAD

**Issue by cblandy** [Esri/map-tour-storytelling-template-js#39]
I have created a hosted Story Map tour. It works on most mobile devices but not all Androids. Version 2.2.8 of the Map Tour fixed the issue on some Androids but not on the Nexus 5 or Note 4. Could it have something to do with the native (linux) Chrome based browser that some Android use in place of a installed Chrome app.

**Comment by glazou** [comment]
The default Android browser used to work, with some UI glitches and poor performance but the tour was opening. That's about what we can expect.
We do recommand using Chrome but I will look on at least making the tour viewable.

**Comment by glazou** [comment]
The default Android browser is beeing deprecated in favor of Chrome on the lastet version http://android.stackexchange.com/questions/100913/what-is-the-default-browser-of-android-5-0-and-above

I have no way to install it back on my device to test so I am not going to be able to fix that issue :/
