### ISSUE TITLE
Map Tour application will not recognize the webmap id if the webmap is created by loading a CSV.

### ISSUE THREAD

**Issue by btelliot** [Esri/map-tour-storytelling-template-js#42]
In previous versions of the map tour template, I could create a map tour by first creating a blank webmap, then loading a CSV, and saving and sharing it publically.  I would then copy the webmap id from the URL of the new web map and paste it into the index.html of the locally hosted application.

In this version of the application, I'm getting a fatal error "An error has occurred Fatal error: Invalid configuration (web map or application identifier not specified in index.html)", even though the identifier is specified in the application.

The web map is properly configured because I can paste the same webmap id into an older version of the application and it will load properly.

Any help with this would be appreciated.

**Comment by glazou** [comment]
Strange, I can't seems to reproduce. Could you share a link to your app?
Are you using the version 2.2.9?

**Comment by btelliot** [comment]
Here is the one using the new version: 
http://ygsftp.gov.yk.ca/LandformAtlas_Draft2/LA_V2/

Here is one using the old version:
http://ygsftp.gov.yk.ca/LandformAtlas_Draft2/LandformAtlas_MapTour/

Both are referencing this webmap:
webmap: "76a63d2a45de49909545dfe2f0eb690f",
http://yukon2.maps.arcgis.com/home/webmap/viewer.html?webmap=76a63d2a45de49909545dfe2f0eb690f

**Comment by glazou** [comment]
You appear to be using the developer version, in which case that's the expected behavior (the message should be clear about that).

Update to that version and you will be good to go http://links.esri.com/storymaps/map_tour_template_zip

**Comment by btelliot** [comment]
Thanks!  This fixed the problem for me.

**Comment by glazou** [comment]
Glad to hear, you are welcome.
