### ISSUE TITLE
New points not showing when using "Feature Collection"

### ISSUE THREAD

**Issue by sverker84** [Esri/map-tour-storytelling-template-js#45]
Long story short:
1. Create a story map tour from a blank map and add points manually from the advanced option -> Start new tour
2. open the web map and save the layer from the web map belonging to the tour
3. This will create a Feature layer of type "Feature Collection"
4. Add this to a new web map and start a new story map tour
5. Add new points
The points added in step 5 only show up in the builder, not when viewing the tour, where only the original points from the saved layer shows up.
There is an http request that gets all the features, both old an new, as json, but after that the original features is fetched from the original feature service, and that's what end up being used.

This is logged as a bug, so I don't know if it is unnecessary to log it here as well?

Defect ID: BUG-000090277
Synopsis: Could not save new tour points at Story Map Tour application which is created from existing feature collection from another web map. 

The reason for saving the layer from web map was that it was used as a form of backup by one of our customers, since there is no other way to export data created with Story Map Tour. (At least no easy way, although we built a python script to take the json data and make it to a properly formatted csv file).

**Comment by glazou** [comment]
Thanks for feedback, can't hurt to report a bug twice :)
We will try to fix for next release and update that issue as well as the support ticket when fixed.

**Comment by glazou** [comment]
A fixed has been deployed to ArcGIS Online.
