### ISSUE TITLE
Use Point layer data in more than one Tab

### ISSUE THREAD

**Issue by cblandy** [Esri/map-tour-storytelling-template-js#48]
This is more of a question than an issue.
I have added two layers to my Web Map to use as Tabs in my Storytelling app. One layer has Public Art locations. The other tab is called Cultural Corridor which contains venues. The venues are inside a polygon layer called Cultural Corridor. I basically want to know if the following is possible. How do I get Public Art locations into the Cultural Corridor tab that are inside the Cultural Corridor. Thus the Cultural Corridor tab will have Venues and Public Art locations (preferably with different colours to differentiate).
Cheers,
Cameron

**Comment by oevans** [comment]
Hi Cameron,

I'm not sure I understand what you are trying to do. Could you please share a link or screenshot of what you have so far to help describe it in more detail? Can you also confirm that you are using the Map Tour app and not a different Story Map app?

As you mentioned this is more of a question than software issue. Would you mind please posting your question to our [GeoNet forum](https://geonet.esri.com/community/gis/web-gis/storymaps) instead and we can help you there?

Thanks!
Owen

**Comment by cblandy** [comment]
Looks like this got posted in the wrong place. I am using the Shortlist template. I will try and post it there. Sorry.

**Comment by oevans** [comment]
No problem, I thought this sounded like Shortlist. ;-) Please post to the [Story Maps GeoNet forum](https://geonet.esri.com/community/gis/web-gis/storymaps) and we can continue to help you from there.  thx!
