### ISSUE TITLE
Map Tour builder fails to launch when it loads at smaller screen sizes

### ISSUE THREAD

**Issue by CraigCleveland** [Esri/map-tour-storytelling-template-js#49]
I've noticed the Map Tour builder fails to launch when it loads at smaller screen sizes.  I believe the intent is correct, which is that the builder is not supposed to be available in mobile form, however I think you may need to take a closer look at it.  The biggest reason this is an issue is that the default browser size upon launch at certain agencies is small enough to cause the issue, and unfortunately changing that default launch size is not something the user has control over…always launches at same size, and then you need to expand.  The issue has been noted as happening across all browsers, and with both Portal for ArcGIS and ArcGIS Online.  The good news is that as soon as the browser is expanded the issue goes away.
 
Possible solutions – 1)  change the verbiage of the message to add something that speaks to expanding browser 2)  force the browser to expand  3)  change the resolution of the limitation.

**Comment by glazou** [comment]
Thanks Craig. 2 and 3 are not doable but we will change the message to make it more explicit.
