### ISSUE TITLE
Error in Maptour configuration

### ISSUE THREAD

**Issue by jha-suraj** [Esri/map-tour-storytelling-template-js#56]
I am using User down load version of maptour and configured this on portal for arcgis. I made following changes in code to get it worked

in index.html
webmap: "",
appid: "83027b1c39ad41f0b97cab1b2425dd19"

in maptour_config.js

Default_Sharing_url:"http://<Portal Ip>/arcgis/sharing/content/items",
Default_proxy_url:""

i have also hosted tour application on server. But while running/accessing the application
i am getting the error: Fatal error :Invalid configuration

Please help me to resolve this issue.

**Comment by jha-suraj** [comment]
Just one thing forgot to add the porta url is working i am supplying is working fine in shortlist template.

**Comment by jha-suraj** [comment]
Just one thing I forgot to add in above question,  the Default_Sharing_url is working fine in shortlist story map template with Default_proxy_url:""

**Comment by glazou** [comment]
Yes if you are using Portal for ArcGIS, you need to edit `app/maptour-config.js` and modify  `DEFAULT_SHARING_URL`

That step is necessary for all templates. `Invalid configuration` likely mean that the app cannot read the configuration file. If the app cannot load the item that you specified it will say "cannot load story".

Are you using that version https://github.com/Esri/map-tour-storytelling-template-js/releases/download/V2.5.0/Storytelling-MapTour-2.5.0.zip

in many case you will also need to edit `DEFAULT_PROXY_URL` but that is not mandatory for the application to start.

I am not sure I can help you much more, I suggest you contact esri support if that doesn't help http://support.esri.com/en/

**Comment by jha-suraj** [comment]
Thanks for your comment I am using the version you mentioned. Please let me know that do I need any other setting besides solid in index.html and  default_sharing_url, default_proxy_url in maptour-config.js.

**Comment by glazou** [comment]
ok that's it. I can only suggest that you open your browser network inspector to see if the request are being sent to your Portal but as I was saying that error make me think your configuration file is not loaded at all, which is typically because you have a typo that makes it not a valid JavaScript. Maybe start from a new download?

**Comment by jha-suraj** [comment]
I don't think the configuration file is not loaded because it is working fine with AGOL. I will look into the request issue. Thanks

**Comment by jha-suraj** [comment]
Hi Gregory, I have checked the traffic on both browser network inspector as well as fiddler and guess request is not being sent to the portal as indicated by trace. But on the other hand same Portal URL is working fine for shortlist template and maptour template is working fine with AGOL. Please suggest if you have any idea.
Thanks

**Comment by glazou** [comment]
Hi,
Made a test and if I edit the configuration to an invalid server

![image](https://cloud.githubusercontent.com/assets/994078/16214133/255037de-370a-11e6-8a95-907966b42feb.png)


I will get this error

![image](https://cloud.githubusercontent.com/assets/994078/16214123/17afe746-370a-11e6-87a8-1cf4827482a8.png)


And see this sort of network traffic

![image](https://cloud.githubusercontent.com/assets/994078/16214116/104c2c58-370a-11e6-9397-b19d4cc33e8d.png)
If I make a mistake in the JSON like

![image](https://cloud.githubusercontent.com/assets/994078/16214156/4c1fd112-370a-11e6-834d-03e772be0665.png)


I will see

![image](https://cloud.githubusercontent.com/assets/994078/16214161/548863fa-370a-11e6-8fa6-3eff6cfe3fdf.png)

As you mentioned getting that last error your JSON must be invalid

**Comment by jha-suraj** [comment]
Thanks for your ideas but there is no error in JSON because it is working fine with AGOL URL. i have configured

DEFAULT_SHARING_URL:http://172.17.123.64/arcgis/sharing/content/items,
DEFAULT_PROXY_URL:""

I have made only above changes in maptour-config.js.

**Comment by jha-suraj** [comment]
Sorry, it was by mistake quotes are there in my code.

**Comment by glazou** [comment]
you also need to remove `http:`
This should works
`DEFAULT_SHARING_URL: "//172.17.123.64/arcgis/sharing/content/items",`

**Comment by jha-suraj** [comment]
Already tested by removing http. same result. One question if i hit  http://172.17.123.64/arcgis/sharing/content/items in browser what it should return. In my case this is returning 400.

**Comment by glazou** [comment]
You for sure need to remove the `http:`, the URL should return a `200`
When you are on the home page of your portal, is it `//172.17.123.64/arcgis/home/index.html` ?

**Comment by jha-suraj** [comment]
Gregory, My question was if i simply hit http://172.17.123.64/arcgis/sharing/content/items in my browser not from code, what it should return?

**Comment by glazou** [comment]
it should return a 200 http code and depending on your configuration you either see the portal directory index or a sign-in page but `400` sounds like this is the wrong url

**Comment by jha-suraj** [comment]
But the same URL is working fine with Shortlist template  but i am getting login page first after login i get my story map.

**Comment by glazou** [comment]
I am not sure I can help you much more, I suggest you contact esri support http://support.esri.com/en/

**Comment by jha-suraj** [comment]
Thanks Gregory for all your support the issue has been resolved now. It was Default_Proxy_URL problem.
