### ISSUE TITLE
"Switch to Builder Mode" appears on map

### ISSUE THREAD

**Issue by Raven4860** [Esri/map-tour-storytelling-template-js#59]
The button for switching modes appears on the map. How can you remove it?

**Comment by glazou** [comment]
That button is designed to appear when you are signed-in as the author of the story so you get an easy access to the builder. In other apps we offer to dismiss the button but we don't yet in MapTour. We will do that in the next revision of the application.

To make sure this is not a bug you can sign-out of your ArcGIS account and the button will disapear.

**Comment by Raven4860** [comment]
Thanks for getting back with me so quickely! I found some code in the
index.html that gets rid of it.
Sorry for the troubles. I am not a developer; I simply dabble.
-Lynnette
