### ISSUE TITLE
Line and polygon features does not show until zooming or panning

### ISSUE THREAD

**Issue by sverkerEsriSE** [Esri/map-tour-storytelling-template-js#62]
We've discovered that when using the Map Tour template in ArcGIS Online, or downloaded and hosted on our own server, a line or polygon layer will not display properly until zoomed in or out a few times, and sometimes also panning is required.

As far as I can tell, this mainly happens in integrated layout, but I have also seen it sometimes with the three-panel layout.

Sometimes it works right away, and sometimes it doesn't, but once you get the layer to display, it will not go away again when zooming or panning.

No parameters are set to hide/show the layer at certain scales etc.

Tested in different browsers and operating systems. (Chrome, Firefox, IE etc.).

An example app is at: http://esrisupport.maps.arcgis.com/apps/MapTour/index.html?appid=b1fef517d3ee4a49ae4eb416bbac9e13

**Comment by sverkerEsriSE** [comment]
Update: three-panel-layout seem to work fine. At least for now.

**Comment by oevans** [comment]
Hi thanks for your feedback. I'm unable to reproduce this using the example app you've shared. The orange feature appears right away for me in all browsers. I would suggest you please work with Esri support to troubleshoot this issue.

![2016-11-03 at 8 22 48 am](https://cloud.githubusercontent.com/assets/3215530/19965714/b933956e-a19e-11e6-8a07-31501b6cfcd4.JPG)

**Comment by sverker84** [comment]
Alright, I will check with Esri Support regarding this. We have reproduced it with different computers and different maps.

**Comment by sverkerEsriSE** [comment]
Alright, I will file a bug with support since we reproduced this with completley different maps on different computers.
