### ISSUE TITLE
src/app/main-app.js is missing

### ISSUE THREAD

**Issue by regan-sarwas** [Esri/map-tour-storytelling-template-js#67]
I cannot get v2.6.1 to run.  Both production and development fail trying to load src/app/main-app.js.  It looks like references to this file were added in the latest commit, but this file is not in the repo ([/src/app](https://github.com/Esri/map-tour-storytelling-template-js/tree/master/MapTour/src/app)).  It is loaded from [index.html](https://github.com/Esri/map-tour-storytelling-template-js/blob/60f1f2e6dbeb20df35a02e445d958943888bea9f/MapTour/src/index.html#L1167).  The [Gruntfile](https://github.com/Esri/map-tour-storytelling-template-js/blob/60f1f2e6dbeb20df35a02e445d958943888bea9f/MapTour/Gruntfile.js#L135) copies it to the deploy folder.

**Comment by cooney** [comment]
Sorry about the @regan-sarwas, the repo has been updated, and the source can be downloaded from: <http://links.esri.com/storymaps/map_tour_template_zip>
