### ISSUE TITLE
Some Basemaps Corrupt Story Map

### ISSUE THREAD

**Issue by regan-sarwas** [Esri/map-tour-storytelling-template-js#69]
Our org has basemaps in our gallery that are built with a WebTiledLayer.  If the user selects one of those in the basemap gallery widget in the builder, then the basemap changes correctly (in builder), and the user can save the story map.  However, the basemap information written to the map item is incorrect, and the story map will no longer open in the viewer.  The user is also unable to open the underlying map item in the AGOL map viewer.

As a work around, the user can open the map item in the AGOL map viewer and change the basemap.  The AGOL map viewer writes a valid map document, and the story map will now open in the viewer with the correct basemap.

**Comment by cooney** [comment]
Thanks @regan-sarwas.  We just did a release and updated the repo, but we may have an opportunity to update the hosted app and repo with your pull request in about a week (Shortlist as well)
